#!/bin/bash

### Loop & push message to firebase

loop_push_message() {
	for i in {1..5}; do
		sleep 2s
		
		curl -X POST \
		-H "Content-Type: application/json" \
		-d '{
		"fields": {
		"content": { "stringValue": "message of bot at '`date +%s`'" },
		"senderID": { "stringValue": "botID" }, 
		"senderName": { "stringValue": "botName" } 
		}
		}' \
		"https://firestore.googleapis.com/v1beta1/projects/fir-chat-4d08f/databases/(default)/documents/channels/channelTestID/messages?&key="$FIREBASE_KEY
	done
}

loop_push_message
